name: Hlidac

on:
  workflow_dispatch:
  schedule:
    - cron: '3-59/10 * * * *'

concurrency:
  group: hlidac
  cancel-in-progress: false

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install requests beautifulsoup4

      - run: python bot.py

      - run: |
          git config --global user.name 'Robot'
          git config --global user.email 'robot@github.com'

          git pull --rebase origin main

          git add log_hlasu.txt
          git commit -m "update" || exit 0
          git push
